language: android
android:
  components:
  - build-tools-21.1.2
  - android-21
  - extra
notifications:
  email:
    recipients:
    - karel@palomamobile.com
    - nisha@palomamobile.com
    on_success: never
    on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: P0VHafLj2m85eeAAuisSOOc5S3QjFFOHhFiqM7ylGhL99Jqr4+uK4O6OxXEG0saaaM/VRe+5uJEWfk/pL49Wwp67gp4F9if10IwchajSfmR6vf/d6joRmlqQol8DiR3gnQ/mmWEwJoXCbnz4bckqmcXxJHt85Qrv0p5DjFLgw1g=
  - secure: 3dV29dGnJM9qicLNBwoLWB+WXpZPpa7jjJUY/nKPyLXjT33+fLLzvMABb+0bFDWTy40PmeiKtRHeidx5dUCgcozHueoF8LF56eT3ePqypGCVLQdbSJ5cCJMoxk/+CxC0YRGA9mUlzwt95vqv64FfZC/RzfwoNZ9u17HCLWzm7t8=
  - secure: klivqdo2cjFt8K/01bTCp7qDaH4teaI3C9z3eeRSogLrWOcGa0l+oXFkMFgW+KzQRHk7yOk3urtBaTaHX8/jZq7N0wnbFH5pmo8IW3ZoQE1wc/4xqhGkw+Splfe+vWR0e5IrRJXdXhLrJCl2pw9rm63BUeDQyJS/IBk999wm5WE=
before_install:
- chmod a+x .utility/initiate-publish.sh
after_success:
- ".utility/initiate-publish.sh"
deploy:
  provider: releases
  user: "${GITUSERNAME}"
  password:
    secure: E1lrE2xAZWqoSaOh2kxjVboBNvqQTCglUlA094CafuYkslv3GHNp4ojqiXirZcXhV20TKY0jCer/JmXiDxzFr8qUVsJKqPQaPxUXfoBWR3uICv3unJ05QmAmD3B6khyDB23MpTIRxJdW5pYIqiPDnD3Djc6Tje+dKEvNY2Cp+4g=
  file: dbMigrationLib*.aar
  skip_cleanup: true
  on:
    tags: false
