language: android
android:
  components:
  - build-tools-21.1.2
  - android-21
  - extra
notifications:
  email:
    recipients:
    - karel@palomamobile.com
    - nisha@palomamobile.com
    on_success: always
    on_failure: always
branches:
  only:
  - master
after_success:
- gradle uploadArchives -PnexusUsername="${SONATYPE_USERNAME}" -PnexusPassword="${SONATYPE_PASSWORD}"
  -Psigning.keyId="${MAVEN_CENTRAL_SIGN_KEY}" -Psigning.password="${MAVEN_CENTRAL_SIGN_PASSWORD}"
  -Psigning.secretKeyRingFile=secring.gpg.gpg
env:
  global:
  - secure: P0VHafLj2m85eeAAuisSOOc5S3QjFFOHhFiqM7ylGhL99Jqr4+uK4O6OxXEG0saaaM/VRe+5uJEWfk/pL49Wwp67gp4F9if10IwchajSfmR6vf/d6joRmlqQol8DiR3gnQ/mmWEwJoXCbnz4bckqmcXxJHt85Qrv0p5DjFLgw1g=
  - secure: 3dV29dGnJM9qicLNBwoLWB+WXpZPpa7jjJUY/nKPyLXjT33+fLLzvMABb+0bFDWTy40PmeiKtRHeidx5dUCgcozHueoF8LF56eT3ePqypGCVLQdbSJ5cCJMoxk/+CxC0YRGA9mUlzwt95vqv64FfZC/RzfwoNZ9u17HCLWzm7t8=
  - secure: Hlkef/sPRsjGC+w0CBXimPu4Lt31pgV4i8dGRZ0MZ0g0Lfw6AEf6oMbHjsESUdtO6qyjD6fLIl8GEdBDUunZZHSbDRciqK8DG2e++vXy/Mp1CVGY6rR/qKLs9jzWwCjFk6Z87T2LYhQwXDkOjAdwdP6OTzBQ892kIS6I2hGHFbE=
  - secure: KD5nUjb1Qoy2pCWPVM/Q5u+HzChXqXk2IJFghMJqJO+O8MIuVxmpdv9F1ttEC/1XfLMI9xmtY0CayHrNfbwMjQVFMtmu6FzDh6TLLQQALdpXVk/1rqffS18JisK+wjXbYf/fqHxQmH368BMun6SbdAayO/ko08AvEHbSEyuqRw4=
  - secure: MLCOcCPX2ZAL/DAD4zOfHcj9gnFVN/kccCi9ZQkMJDtJ2I2lDIP854O+6pDGwcV4+JvhRjW38qdATIvEIDnvDkAh+wk5RPZpgt8z4VvjGznMPGnA6B/Ce085Qra6mhVNbfgH8GmdWdPBwy+ePdjJfUx+iqFgs6Ur6vyqwh1wGr0=
before_install:
  - echo gpg --passphrase "${SECRET_KEY_SIGN_PASSWORD}" secring.gpg.gpg