language: android
android:
  components:
  - build-tools-21.1.2
  - android-21
  - extra
notifications:
  email:
    recipients:
    - karel@palomamobile.com
    - nisha@palomamobile.com
    on_success: always
    on_failure: always
branches:
  only:
  - master
after_success:
- initiate-publish.sh