language: android
android:
  components:
  - build-tools-21.1.2
  - android-21
  - extra
notifications:
  email:
    recipients:
    - karel@palomamobile.com
    - nisha@palomamobile.com
    on_success: never
    on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: P0VHafLj2m85eeAAuisSOOc5S3QjFFOHhFiqM7ylGhL99Jqr4+uK4O6OxXEG0saaaM/VRe+5uJEWfk/pL49Wwp67gp4F9if10IwchajSfmR6vf/d6joRmlqQol8DiR3gnQ/mmWEwJoXCbnz4bckqmcXxJHt85Qrv0p5DjFLgw1g=
  - secure: 3dV29dGnJM9qicLNBwoLWB+WXpZPpa7jjJUY/nKPyLXjT33+fLLzvMABb+0bFDWTy40PmeiKtRHeidx5dUCgcozHueoF8LF56eT3ePqypGCVLQdbSJ5cCJMoxk/+CxC0YRGA9mUlzwt95vqv64FfZC/RzfwoNZ9u17HCLWzm7t8=
before_install:
 - chmod a+x .utility/initiate-publish.sh
after_success:
- .utility/initiate-publish.sh