language: android

android:
    components:
      - build-tools-21.1.2
      - android-21
      - extra

notifications:
  email:
    recipients:
      - karel@palomamobile.com
      - nisha@palomamobile.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always

branches:
  only:
    - master
