language: android

android:
    components:
      - build-tools-21.1.2
      - android-21
      - extra

notifications:
  email:
    - karel@palomamobile.com
    - nisha@palomamobile.com

branches:
  only:
    - master
