language: android
  android:
    components:
      - build-tools-21.1.2
      - android-21
      - extra

  notifications:
    email: false

  before_install:

    # for gradle output style
    - export TERM=dumb

    # environment info
    - ./gradlew -v
    - uname -a

  # Let's try to build...
  script: ./gradle clean build